name: mechanic_discovery_app
description: A frontend Flutter project for the Flask backend (project491).
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.2
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  animations: ^2.0.7
  google_fonts: ^4.0.4
  liquid_swipe: ^3.1.0
  flutter_map_marker_cluster: ^1.1.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
